### ISSUE TITLE
Wrong path in build instructions?

### ISSUE THREAD

**Issue by dnfgh** [alandtse/CommonLibVR#23]
Trying to build this project,

`
\CommonLibVR>cmake --preset vs2022-windows-vcpkg-vr
Preset CMake variables:

  BUILD_SKYRIMVR:BOOL="TRUE"
  CMAKE_BUILD_TYPE:STRING="Release"
  CMAKE_CXX_FLAGS="/EHsc /MP /W4 /WX /external:anglebrackets /external:W0 "
  CMAKE_MSVC_RUNTIME_LIBRARY:STRING="MultiThreaded$<$<CONFIG:Debug>:Debug>DLL"
  CMAKE_TOOLCHAIN_FILE:STRING="/scripts/buildsystems/vcpkg.cmake"
  VCPKG_TARGET_TRIPLET:STRING="x64-windows-static-md"
`

According to this there should be a vcpkg.cmake in /scripts/buildsystems/
but /buildsystems/ wasnt created.

**Comment by dnfgh** [comment]
Actually following these instructions: https://github.com/microsoft/vcpkg#quick-start-windows
```
In order to use vcpkg with Visual Studio, run the following command (may require administrator elevation):

> .\vcpkg\vcpkg integrate install

````

and then running 

```
cmake --preset vs2022-windows-vcpkg-vr -DCMAKE_TOOLCHAIN_FILE=C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake
```

allowed me to build it

**Comment by alandtse** [comment]
Oh sorry that I missed this but I'm glad you figured it out.
