### ISSUE TITLE
Possibly shifted default object enum values

### ISSUE THREAD

**Issue by Seally** [alandtse/CommonLibVR#3]
Hi,

I think at least some of the `DEFAULT_OBJECT` enum values in [BGSDefaultObjectManager.h](https://github.com/alandtse/CommonLibVR/blob/cda29f87597e7f3d3458be8725e51313141a4863/include/RE/B/BGSDefaultObjectManager.h#L9) may have been shifted for VR. 

I'm currently working on a (blind) port for VR for [YASTM](https://github.com/Seally/yastm) and the logs a user provided suggests that `DEFAULT_OBJECT::kKeywordReusableSoulGem` does not actually point to this keyword (whatever it fetched fails to identify reusable soul gems). 

Since I do not own Skyrim VR at all, I'm afraid I'll have to trouble you to look into this if you can spare the time. I'm assuming that the survival mode stuff shouldn't be in there at least.

Thanks, and I apologize for the trouble.

**Comment by alandtse** [comment]
Sorry I didn't see this till now (notifications weren't on). Do you want to send over the dll and pdb and I can see if I can break and explore?

**Comment by Seally** [comment]
I'm not sure how sending the specific DLL will help, just that whatever ID the reusable soul gem keyword is, it's probably not 216 (since my checks on known reusable soul gems fail on a user's machine).

The offending lines from my plugin are here. 

https://github.com/Seally/yastm/blob/20dd13d00c21d1da0856c1cc4f33e0bcc451b547/src/utilities/misc.cpp#L54-L63

I think it might be better to create a plugin that hooks `kDataLoaded` to dump what's in them and compare with the enum values.

Note: I've attached an FOMOD since the plugin doesn't quite work without the rest of the files. Basically the reusable soul gem keyword check seems to be failing in the logs (at least on the user's machine, since I don't have a way of running it myself).

[YASTM_VR.zip](https://github.com/alandtse/CommonLibVR/files/7978210/YASTM_VR.zip)

**Comment by alandtse** [comment]
Thanks. I'll see about dumping kDataLoaded. I had thought you were iterating through the objects so I could debug it with a break, but now that I see how you did it I get it.

**Comment by alandtse** [comment]
Please check with the latest commit to VR
