### ISSUE TITLE
NG / Example

### ISSUE THREAD

**Issue by Keidran** [alandtse/CommonLibVR#42]
How can I use this project? Is there an example?

**Comment by SteveTownsend** [comment]
There are *many* projects that use the library that you can use as
examples. "Best" example depends on what you want to do, the functional
coverage is broad.

**Comment by Keidran** [comment]
@SteveTownsend, projects I found usually referenced vcpkg with an old version (3.7.0) or not NG.

**Comment by SteveTownsend** [comment]
I have heard that this works as a drop-in replacement for CharmedBaryon's
repo, but I confess I have not yet tried that.

**Comment by alandtse** [comment]
CrashloggerSSE and Community Shaders uses this.
