### ISSUE TITLE
IMenu functions returning incorrect flags

### ISSUE THREAD

**Issue by AtomCrafty** [alandtse/CommonLibVR#51]
The flag values returned by [these functions](https://github.com/alandtse/CommonLibVR/blob/vr/include/RE/I/IMenu.h#L115-L119) don't match the respective function names, but are shuffled around. Probably not a big deal since those don't sound like the most commonly used functions, but that doesn't look intentional.

**Comment by alandtse** [comment]
Thanks. Feel free to submit a PR. It may make sense to do it in an upstream fork line po3s and we'll get the fix when we sync.

**Comment by AtomCrafty** [comment]
Done
https://github.com/powerof3/CommonLibSSE/pull/109

**Comment by alandtse** [comment]
Awesome thanks. I'll see about syncing again with po3.

**Comment by alandtse** [comment]
Actually, let's leave it open until I've done the sync else I'll forget.

**Comment by alandtse** [comment]
This should be all in for VR/NG. Thanks!
