### ISSUE TITLE
CTD with TESDataHandler::LookupLoadedModByIndex

### ISSUE THREAD

**Issue by muenchk** [alandtse/CommonLibVR#9]
When using TESDataHandler::LookupLoadedModByIndex, a CTD occurs if the plugin is not found.

Example:
`RE::TESDataHandler* datahandler = RE::TESDataHandler::GetSingleton();`
`RE::TESFile* file = datahandler->GetLoadedModByIndex(0xF3);`

crashes when there is no mod with index 0xF3. 
The crash occurs in line 95:
`			if (file->compileIndex == a_index) {`
due to a null dereference on `file`, which occurs due to the usage of a static array in VR.

Changing the line to 
`			if (file && file->compileIndex == a_index) {`
fixes the issue.

The same issue should also occur in line 78, when trying to find a plugin that is not present.

**Comment by alandtse** [comment]
Thanks. Feel free to submit a PR or I'll get to it next time I do a revision.
